### ISSUE TITLE
Governance: make service_principal_all_owner_name optional 

### ISSUE THREAD

**Issue by CalleB3** [XenitAB/terraform-modules#1138]
service_principal_all_owner_name is currently mandatory to input, there are cases where we dont want to force this.
e.g when `delegate_sub_groups = false` and we havent created  the all-owner, all-contributor, all-readers groups.

Implement the same logic as we currently use in `aad-group-sub-delegation.tf` so that it will be controlled via the `delegate_sub_groups` variable.

@linus-lysell  brough this issue

**Comment by landerss1** [comment]
Fixed by [#1139](https://github.com/XenitAB/terraform-modules/pull/1139).
