### ISSUE TITLE
Add dns_settings to vnet_config in Core module

### ISSUE THREAD

**Issue by tvuorenmaa89** [XenitAB/terraform-modules#152]
We are missing dns_settings at vnet_config to set DNS settings at Vnet level.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network#dns_servers

**Comment by simongottschlag** [comment]
@tvuorenmaa89 released: https://github.com/XenitAB/terraform-modules/releases/tag/2021.03.2
