### ISSUE TITLE
Add litmuschaos

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/terraform-modules#174]
https://litmuschaos.io/

**Comment by simongottschlag** [comment]
@phillebaba thoughts?

**Comment by NissesSenap** [comment]
Me and phillebaba have spoken recently about https://litmuschaos.io/ 
There are great examples: https://hub.litmuschaos.io/ on tests that we can run. Specific for infrastructure but also can also easily help customers to use it with there applications.
And of course we can use it with ours.

**Comment by simongottschlag** [comment]
@NissesSenap 👍

**Comment by landerss1** [comment]
Implemented in #1260
