### ISSUE TITLE
Should we use conventional commits?

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/terraform-modules#208]
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by simongottschlag** [comment]
@XenitAB/team-devops vote with 👍👎

**Comment by NissesSenap** [comment]
Great idea

**Comment by phillebaba** [comment]
This sounds like a complex standard, is there a way to automatically verify all commit messages in a PR?

**Comment by simongottschlag** [comment]
@phillebaba I'm looking for a way to easily handle the changelog and auto generate it.

**Comment by NissesSenap** [comment]
We will instead go with: https://github.com/XenitAB/terraform-modules/issues/406
