### ISSUE TITLE
Override subnet naming convention - Core Module

### ISSUE THREAD

**Issue by tvuorenmaa89** [XenitAB/terraform-modules#337]
In Azure there are multiple subnets used by services that need to follow a specific naming convention. 

Example: 
AzureBastionSubnet - For Azure Bastion
GatewaySubnet - For VPN Gateway

Can we introduce a azure_service flag to override the naming convention and only use the name provided in the Subnet block?

**Comment by simongottschlag** [comment]
I would prefer this not being part of the main logic. Perhaps we should create a separate variable like `extra_subnets`?

CC @NissesSenap @phillebaba

**Comment by simongottschlag** [comment]
@tvuorenmaa89 what do you think about this idea?

We add output for the vnet, subnets and routes and if someone wants to create additional subnets they can do it using the outputs? That would mean we don't need to add logic to our modules for this, but make it easy to add outside the module if needed.

**Comment by tvuorenmaa89** [comment]
Sounds good to me @simongottschlag , and i like the idea not to build in logic if not needed as in this case.

**Comment by simongottschlag** [comment]
Released: https://github.com/XenitAB/terraform-modules/releases/tag/2021.08.2
