### ISSUE TITLE
postgres module to manage users together with azure AD

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/terraform-modules#387]
We want to be able to support using MSI in a smooth way together with azure postgres.
Today this is not possible in terraform thanks to how the sql queries needs to be performed.

Our plan is to write a new terraform provider and it's only role is to be able to manage this.

**Comment by phillebaba** [comment]
The end product should be a reusable module which configures MSI in a Azure Postgres instance, I am not sure if it should also create the postgres instance in the module. My worry about it is that it will require massive amounts of variables to fit everyones need. It may be good to start by setting up a best practice module which works for most people.

As mentioned the biggest blocker right now is how postgres should be configured. The current postgres providers do not support the required use cases, so there will be a need to develop a provider to do this configuration.

**Comment by landerss1** [comment]
XKS per se doesn't require any PostgreSQL instances. Rather, this is an application feature that would be beneficial to customers and possibly our own eID service. However, given the amount of work required I can't see that the benefits would make it worthwhile. Also, we recently added support for Azure Service Operator, which offers an alternative way of creating and managing PostgreSQL instances. Therefore, I'm closing this issue.
