### ISSUE TITLE
CSI driver AWS update helm chart

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/terraform-modules#403]
Today I have written a very basic helm chart to deploy csi-secrets-store-provider-aws
https://github.com/XenitAB/terraform-modules/tree/main/modules/kubernetes/csi-secrets-store-provider-aws/charts/csi-secrets-store-provider-aws

There is a PR open to solve this upstream: https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/35
This solution is very similar to the Azure one and it would be great for us but sadly AWS isn't responding on the PR...

IF AWS finally merges the PR then we should update our solution as well.

**Comment by landerss1** [comment]
Won't do. Support for AWS has been removed.
