### ISSUE TITLE
Support resource naming override

### ISSUE THREAD

**Issue by tvuorenmaa89** [XenitAB/terraform-modules#501]
### Description

When using the core module to deploy resources there we have identified a need to override the standard naming of resources. 

**Scenario 1 - Subscription short name** 

When using the core-module to deploy multiple core setups in customers environments we will end up with multiple resources with the same name. This is because we use the core-module to deploy any kind of Landing zones in Azure.

**Example:** 
Using the core module multiple times will result in multiple virtual networks called vnet-prod-we-core.

Suggestion: 
Would it be possible to introduce subscription short as a optional attribute in the naming? 
**vnet-prod-we-lzvw-core** where lzvw is shorten for Landing zone Virtual Workspace. 

**Scenario 2 - CAF Naming Convention / Customer specific**

Microsoft have a naming convention in Azure which we try to align to but it does not follow a strict pattern: 

**Example:**
Subnet - 'snet-subscription-region-###'
Public  IP - pip-"vm name or app name"-environment-region-###
Route Table - route-"route table name"

More examples: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming

In this case it would be useful to be able to override the naming convention to align with CAF. 
The same scenario goes for deployments where customer have a established naming convention we need to follow for new resources.

**Comment by simongottschlag** [comment]
@ahockersten can you make sure we get started with this? Please and thank you. 😊
