### ISSUE TITLE
Grafana log agent is affected by tolerations

### ISSUE THREAD

**Issue by bittrance** [XenitAB/terraform-modules#526]
A cluster with node groups that limits scheduling may stop the Grafana log agent from deploying on those node pools. This means there are no logs reported from pods on that node pool which is unlikely to be what you want. Probably, the Grafana log agent should ignore all such limits.

**Comment by jimgus** [comment]
Fixed by this PR: https://github.com/XenitAB/terraform-modules/pull/527
