### ISSUE TITLE
Kubernetes 1.22 Support

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#562]
Kubernetes 1.22 removes a couple of API versions. The major one being all older versions of Ingress.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

Certain modules have to be updated before clusters can be upgraded to 1.22. This is a blocker until this issue is closed.

Tasks:

- [x] #565
- [x]  Update all modules creating Ingress resources to use networking.k8s.io/v1 
- [x] Check external-dns and cert-manager still work with their current versions
- [x] #536
- [x] Identify other breaking changes due to API Version removal
- [ ] Test deployment on 1.22

**Comment by NissesSenap** [comment]
This is now solved and we are running k8s 1.22 in production.
