### ISSUE TITLE
EKS shared OIDC provider

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#592]
It seems like it is possible to add additional OIDC providers to an EKS cluster, according to this comment.
https://github.com/aws/amazon-eks-pod-identity-webhook/issues/23#issuecomment-1046088690

Here is some documentation and the Terraform resource to configure this.
https://aws.amazon.com/blogs/containers/introducing-oidc-identity-provider-authentication-amazon-eks/
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_identity_provider_config

We should explore the possibility to do replace the OIDC provider the EKS cluster comes with, with a shared OIDC provider which would be used with multiple clusters in a B/G situation.

**Comment by landerss1** [comment]
Won't do. Support for AWS has been removed.
