### ISSUE TITLE
Block creating ingress without ingress class

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#605]
It seems like it is possible at times to create a Ingress without an Ingress class. Not really sure why this happens. A solution to the problem is to disallow creating Ingresses without a class, which should never happen because the default ingress class should mutate any Ingress without a class.

**Comment by NissesSenap** [comment]
This should be handled in: https://github.com/XenitAB/terraform-modules/pull/651

**Comment by phillebaba** [comment]
Closing as it is fixed.
