### ISSUE TITLE
Use Azure Workload Identity instead of aadpodidentity

### ISSUE THREAD

**Issue by CalleB3** [XenitAB/terraform-modules#693]
We should look in to replacing aad pod identity with azure workload identity

**Comment by NissesSenap** [comment]
Still waiting for Workload identity to become GA in AKS.

**Comment by phillebaba** [comment]
Feature looks to still be in preview.
https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview

**Comment by landerss1** [comment]
This was implemented by PR [1103](https://github.com/XenitAB/terraform-modules/pull/1103),  [1082](https://github.com/XenitAB/terraform-modules/pull/1082),  [1076](https://github.com/XenitAB/terraform-modules/pull/1076),  [1069](https://github.com/XenitAB/terraform-modules/pull/1069),  [1067](https://github.com/XenitAB/terraform-modules/pull/1067),  [1066](https://github.com/XenitAB/terraform-modules/pull/1066) and  [988](https://github.com/XenitAB/terraform-modules/pull/988). Closing this issue.
