### ISSUE TITLE
Chart removed in ingress-healthz bitnami/nginx 

### ISSUE THREAD

**Issue by qhris** [XenitAB/terraform-modules#696]
It appears that the helm repository <https://charts.bitnami.com/bitnami> removed version 9.5.10 (and others) yesterday so the `ingress-healthz` module will fail to install.

Ran into this yesterday when trying to spin up a cluster, worked in the morning, but in the afternoon the chart was gone.

**Comment by phillebaba** [comment]
Yes bitnami has removed a lot of their entries in index.yaml to decrease bandwidth use. We should look at moving to OCI charts long term.
