### ISSUE TITLE
AKS CSI driver managed by AKS?

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/terraform-modules#785]
Recently AKS enabled a feature to let azure manage the installation of CSI driver for you.
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

This is also possible from terraform:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#secret_rotation_enabled

Is this something that we want let Azure do for us so we don't have to manage the helm chart?
Discuss and decide

**Comment by landerss1** [comment]
Done. We now specify `key_vault_secrets_provider` in the kubernetes cluster definition.
