### ISSUE TITLE
Missing allow_gateway_transit argument for azurerm_virtual_network_peering

### ISSUE THREAD

**Issue by tvuorenmaa89** [XenitAB/terraform-modules#803]
Hi Team, 
When using the use_remote_gateway argument on a spoke-vnet we need to set allow_gateway_transit on the hub-side to allow tansit.
Today we do not have this configurable on neither core or hub-module.

[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_peering#allow_gateway_transit ](url)

**Comment by simongottschlag** [comment]
@tvuorenmaa89 do we need this asap or is it just nice to have? We're waiting for a feature that will be released in hopefully a few days (or maybe more realistically a few weeks) that makes it possible to add optional parameters. This will be released in terraform 1.3.

**Comment by tvuorenmaa89** [comment]
> @tvuorenmaa89 do we need this asap or is it just nice to have? We're waiting for a feature that will be released in hopefully a few days (or maybe more realistically a few weeks) that makes it possible to add optional parameters. This will be released in terraform 1.3.

@simongottschlag  We can for sure wait for the the optional parameters feature to be released.
