### ISSUE TITLE
Add Service Deligation for subnets in Core module 

### ISSUE THREAD

**Issue by linus-lysell** [XenitAB/terraform-modules#845]
Is it possible to add service delegation for subnets in the core module. 

Se example here: 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet
```terraform
 delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.ContainerInstance/containerGroups"
      actions = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"]
    }
  }
}
```

**Comment by simongottschlag** [comment]
@linus-lysell we are already creating a group for service endpoint join. What else is needed other than that?

**Comment by linus-lysell** [comment]
@simongottschlag Thanks for the quick reply! Service endpoint is working fine. I would need the delegation block as a feature in the core module.
