### ISSUE TITLE
Reduce metrics usage

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#859]
I think that we are currently collecting a lot more metrics than we actually need. This is due to scraping at higher than needed frequencies, large cardinalities in time series, and histogram buckets that are to granular.

Currently the default scrape interval in Prometheus is 30 seconds. If we increase the default scrape interval to 60 seconds we can save a large amount of extra data. My guess is that we do not need to scrape that often anyways for most of the metrics, and for those that we do we should set a specific value for the scrape interval.

I have identified time series which a high count by calling `/api/v1/status/tsdb`. Below is a list of time series and a suggested solution to the problem.

| Time Series | Issue | Proposal |
| --- | --- | --- | 
| apiserver_request_duration_seconds_bucket | The time series contains labels group, namespace, resource, scope, verb, version. Which creates large amounts of time series. | We should drop this metric all together. We are not in control of the API server so I do not see how we would need this. An alternative would be to drop a bunch of the labels which differentiate between different resources. |
| apiserver_request_slo_duration_seconds_bucket | Same as above. | Same as above. |
| promtail_log_entries_bytes_bucket | The path label contains a unique value for every single file that is being scraped. | We should either drop the path label or drop the metrics all together. |
| etcd_request_duration_seconds_bucket | Contains a type label which is unique for each resource type stored in etcd. | Should probably be dropped as the metrics is not being used at all. |
| nginx_ingress_controller_request_duration_seconds_bucket | Creates a lot of time series just because it has a bucket per ingress and target. The high cardinality comes from the combination of ingress controller and target pod. | Not sure what to do with this one, maybe it should be left alone for the time being until it becomes the metric with the most amount of active time series. |
| container_.* | All metrics prefixed with container_ that are scraped from the kubelet contains a large amount of metrics. This is because it collects information about every container on every node. | I think there are ways to limit the cardinality, but honestly if we are not using the metrics we should probably just drop them all together. |

Good resources to read:
* https://grafana.com/blog/2022/10/20/how-to-manage-high-cardinality-metrics-in-prometheus-and-kubernetes/
* https://source.coveo.com/2021/03/03/prometheus-memory/

**Comment by NissesSenap** [comment]
From reading your comments it sounds really reasonable to delete all of the time series that you point to.

`nginx_ingress_controller_request_duration_seconds_bucket` and `container_.*` is the big question marks.
Is there any dashboard that uses any of them?

**Comment by jimgus** [comment]
Some container_* metrics are used by the mixins dashboards. I kept some of them for grafana tenants (maybe too many) in this PR in order to be able to use some mixins dashboards: https://github.com/XenitAB/terraform-modules/pull/857

**Comment by jimgus** [comment]
I think it should be ok to drop `promtail_log_entries_bytes_bucket`

**Comment by NissesSenap** [comment]
@phillebaba  would be interesting to see if we could do https://github.com/XenitAB/terraform-modules/pull/875 as well.
I think prometheus and grafana_agent currently is fighting about the prometheus CRD:s.
So it would be nice if we can fix that at the same time, especially if we need to do something manually on all the clusters.

**Comment by NissesSenap** [comment]
Since we have implemented a number of fixes I will close this issue.
This is of course something we will keep on working on in the future.
