### ISSUE TITLE
Add support for OTLP ingestion in datadog-operator

### ISSUE THREAD

**Issue by slarwise** [XenitAB/terraform-modules#872]
Open telemetry ingestion by the datadog agent was added to the datadog operator in this PR https://github.com/DataDog/datadog-operator/pull/597/files.

To enable this, see example here https://github.com/DataDog/datadog-operator/blob/main/examples/datadogagent/datadog-agent-otlp.yaml

This was added in https://github.com/DataDog/datadog-operator/releases/tag/v1.0.0-rc. We should probably wait with upgrading the datadog-operator until 1.0 is officially released.

**Comment by slarwise** [comment]
Related: https://github.com/XenitAB/terraform-modules/pull/955

**Comment by CalleB3** [comment]
Related: #982

**Comment by CalleB3** [comment]
Solved in #1000

**Comment by slarwise** [comment]
🥳🥳🥳
