### ISSUE TITLE
Add priotiy class

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#91]
System pods that are critical for functionality to work should have pre emptive priority to be able to kick other pods out. This is especially true for apps with daemonsets that have to run on all the nodes.

Examples of pods that need priority class:

* aad pod identity
* datadog
* csi secret store
* gatekeeper

**Comment by NissesSenap** [comment]
https://github.com/XenitAB/terraform-modules/pull/278 this partly solves this issue.
The following is still needed to get defined.

- linkerd
- datadog
- fluxcd v1
- velero
- azdo-proxy
- gatekeeper (should be fixed in next release)
- reloader
-ingress-healthz (bitnami nginx)

**Comment by phillebaba** [comment]
I agree, this issue should be kept open until we feel like all critical pods have a set priority class.

**Comment by phillebaba** [comment]
azdo-proxy will be solved in the next release

**Comment by phillebaba** [comment]
Closing as gatekeeper has now been released with fixed priority classes.
