### ISSUE TITLE
set priorityClass x509 helm chart

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/terraform-modules#913]
Recently we started to use x509 helm chart.
At the time it didn't have prirotiyClass in it, https://github.com/enix/x509-certificate-exporter/pull/91
The new helm chart containing the change is currently in beta.

Waiting for the new feature to get released.

**Comment by landerss1** [comment]
Fixed by [a4b0a66](https://github.com/XenitAB/terraform-modules/commit/a4b0a66cf0feadc12fbc1b67cdf5db08dd740965).
