### ISSUE TITLE
Route table - disable_bgp_route_propagation

### ISSUE THREAD

**Issue by linus-lysell** [XenitAB/terraform-modules#923]
Hi, 

Is it possible to add "disable_bgp_route_propagation" flag into the "route_config"? 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/route_table
<img width="407" alt="image" src="https://user-images.githubusercontent.com/95033863/215797434-47212acb-cad6-4c16-9a79-42eaf07639b1.png">

Thanks in advance!

**Comment by simongottschlag** [comment]
@linus-lysell I think so! And now we also have optional for the variables which makes this even easier to keep backward compatibility.

Can you create a PR for it? I'll help you with a code review 👍
