### ISSUE TITLE
VNET Peering - Adding "allow_gateway_transit" as optional in the core module

### ISSUE THREAD

**Issue by linus-lysell** [XenitAB/terraform-modules#929]
Hi, 

Do you see any problems with adding "allow_gateway_transit" as optional in the core module? 

I need this setting to configurate peering in the virtual network from the HUB. This setting will make this configuration possible: 

<img width="328" alt="image" src="https://user-images.githubusercontent.com/95033863/217225788-1ac7f96e-0d28-48d8-a1f0-f5230e86f440.png">

Thanks in advance!

**Comment by simongottschlag** [comment]
Hi @linus-lysell!

I don't see any issue right now, but please create a PR for it and we'll review it. 😊👍
