### ISSUE TITLE
Log RG required in core module

### ISSUE THREAD

**Issue by Sk1llberg** [XenitAB/terraform-modules#930]
In core module, under log.tf the resource group is required and mapped as a datasource. No documentation or other references for creation is mentioned before. Shouldn't it be created by default in governance module or atleast documented?
https://github.com/XenitAB/terraform-modules/blob/9e13a048abe2c73ea203466526d27ebda214c4e1/modules/azure/core/log.tf#L1

**Comment by NissesSenap** [comment]
Hmm I underestimated how painful it would be to set a default value that contains lab without making a breaking change.
It's possible but readability goes down way to much.

Sadly I think we will have to stick to just doing a quick documentation update to fix this.
I will fix that in a PR.
