### ISSUE TITLE
Core/azurerm_subnet: Make "private_endpoint_network_policies_enabled" configurable 

### ISSUE THREAD

**Issue by linus-lysell** [XenitAB/terraform-modules#942]
Hi, 

Do you see any problems with making "private_endpoint_network_policies_enabled" configurable as an optional variable in the Core module? 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#private_endpoint_network_policies_enabled
https://learn.microsoft.com/en-us/azure/private-link/disable-private-endpoint-network-policy?tabs=network-policy-portal

Please let me know if you have any questions. 

Thanks in advance!

**Comment by NissesSenap** [comment]
Go nuts @linus-lysell , feel free to create a PR.
