### ISSUE TITLE
Migrate away from looping regions inside of the module

### ISSUE THREAD

**Issue by phillebaba** [XenitAB/terraform-modules#95]
We should consider moving away from looping regions inside of the modules before it is too late to make the switch. Doing the looping outside will greatly simplify the complexity as we dont have to generate env region variables.

**Comment by phillebaba** [comment]
@simongottschlag

**Comment by simongottschlag** [comment]
Finished:
- azure/governance: #124 
- azure/core: #125 
- azure/hub: #126
